version: '3'

services:
  ros2:
    build:
      context: ./
      dockerfile: ros2.Dockerfile

  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://172.16.200.52:11311"
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
